# Generated by Django 4.0.3 on 2022-03-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('rasm', models.FileField(upload_to='bolimlar')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('batafsil', models.TextField()),
                ('narx', models.IntegerField()),
                ('rasm', models.FileField(upload_to='mahsulotlar')),
                ('chegirma', models.PositiveSmallIntegerField()),
                ('vazn', models.PositiveIntegerField()),
                ('brend', models.CharField(max_length=30)),
                ('mamlakat', models.CharField(max_length=30)),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.bolim')),
            ],
        ),
    ]
